/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/mobi/About.vue')['default']
    AboutCertificate: typeof import('./components/AboutCertificate.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    ContactUs: typeof import('./components/ContactUs.vue')['default']
    ContactUsModal: typeof import('./components/ContactUsModal.vue')['default']
    CoreTech: typeof import('./components/mobi/CoreTech.vue')['default']
    DataProduct: typeof import('./components/mobi/DataProduct.vue')['default']
    DownloadDoc: typeof import('./components/DownloadDoc.vue')['default']
    Home: typeof import('./components/mobi/Home.vue')['default']
    HomeAdvantage: typeof import('./components/HomeAdvantage.vue')['default']
    HomePartner: typeof import('./components/HomePartner.vue')['default']
    HomeSolution: typeof import('./components/HomeSolution.vue')['default']
    MobiHome: typeof import('./components/mobi/MobiHome.vue')['default']
    ModuleTitle: typeof import('./components/ModuleTitle.vue')['default']
    NewsMobi: typeof import('./components/mobi/news-mobi.vue')['default']
    ProductsComputed: typeof import('./components/ProductsComputed.vue')['default']
    ProductsPlatform: typeof import('./components/ProductsPlatform.vue')['default']
    ProductsUse: typeof import('./components/ProductsUse.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechnologyCore: typeof import('./components/TechnologyCore.vue')['default']
    TechnologyPag: typeof import('./components/TechnologyPag.vue')['default']
    TechnologyStructure: typeof import('./components/TechnologyStructure.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheMobiHeader: typeof import('./components/TheMobiHeader.vue')['default']
  }
}
